<?php
$tab = array(
  '1' => 'Connection',
  '2' => 'Register',
  '3' => 'Visit the descriptions below',
  '4' => 'Apply for a job',
  '5' => 'CONTACT-US',
  '6' => 'Sign in',
  '7' => 'Login',
  '8' => 'Password',
  '9' => 'Cancel',
  '10' => 'Sign up',
  '11' => 'Sign up video_recrut',
  '12' => 'Last name',
  '13' => 'First name',
  '14' => 'Phone Number',
  '15' => 'Validate',
  '16' => 'Welcome',
  '17' => 'Sign out',
  '18' => 'Wrong login/password.Try again',
  '19' => 'Add job',
  '20' => 'List candidate',
  '21' => 'Job name',
  '22' => 'Type of agreement ',
  '23' => 'Job description',
  '24' => 'Expertise required',
  '25' => 'Job',
  '26' => 'LIST OF CANDIDATURES'
);
 ?>
